### ISSUE TITLE
deb deploy script 

### ISSUE THREAD

**Issue by fizzyade** [AaronDMarasco/pingnoo#1]
The makedeb is wrapped with the message_printer object at the deploy.py, this differs to the behaviour for rpm's where the makerpm.py uses message_printer, this allows you to wrap individual parts of the rpm process with message_printer for more detailed output.

As makedeb is wrapped at a higher level, message_printer (or any output for that matter) cannot be used as it will appear in the same line as the creating message.

**Comment by AaronDMarasco** [comment]
Just wrapped this up with lots of feedback and a few other misc tweaks. 

5261e1bec7b0188cdea

See also  nedrysoft/pingnoo#38
