### ISSUE TITLE
Arch support

### ISSUE THREAD

**Issue by fizzyade** [AaronDMarasco/pingnoo#2]
I added support for arch based distributions to the deployment script, although I do need to figure out the best way of holding the AUR as it requires the full source code tarball which I'm hosting on my website, but I need to push that to the server and also push the PKGBUILD, .SRCINFO and install script to the AUR repo, there's a bit of a chicken and egg situation regarding the AUR that involves me manually moving files around and uploading and then pushing to git.

**Comment by AaronDMarasco** [comment]
@fizzyade I've never done an AUR but we might already have an 80% solution. The way the RPMs are made generates a temporary tarball from the git clone with the bare minimum files. Might be able to leverage that.

**Comment by fizzyade** [comment]
The arch stuff is all working, it was a cut and paste of the other make<something>.py scripts.

I've just fixed the building of the arch package, replacing the file URL with a template variable which when called from the deployment script uses a file:// URL.

I've created a PHP script on my server to allow me to upload the source tarball, I just need to create a script makes use of makepkg.py to upload the generated tarball and then updates the AUR repo with the PKGBUILD (that has the real URL rather than the file:// one).

This script will only of use to myself as only I can upload to the AUR, additionally I need the script to upload the debian, fedora and ubuntu packages to packagecloud where they're being hosted so the flavour of package manager on the distro can be used to install.

And finally, create a release on GitHub and upload all the generated deployable images to GitHub.

**Comment by AaronDMarasco** [comment]
OK; why is this an issue here then? Did you want a code review on it or something?

**Comment by fizzyade** [comment]
I just wanted to give you a heads up I that I’d modified it again, there may be better ways of doing some of the bits and pieces, but as I mentioned before, I’m more of a casual python programmer and I appreciate and are grateful for the work on the script you’ve done already.

**Comment by AaronDMarasco** [comment]
Python prefers `snake_case` but you changed `deb_create` to `debCreate`; otherwise there wasn't really any content; LGTM.

**Comment by fizzyade** [comment]
cheers.  I'll remember for future, not to camelcase, I'll fix up the camelcase->snake case this week.  I'm just switching from using PowerShell in the windows script to zip up the portable edition to using the zipfile object in python as I need to merge in the visual studio runtime.
